### ISSUE TITLE
Clone fails with no --cspec provided.

### ISSUE THREAD

**Issue by scottedsa** [ezrapagel/knife-vsphere#13]
Clone fails when trying to specify all information without the 'cspec':

```
# knife vsphere vm clone -VV testbox01 --folder templates --template CentOS_6.0-clean --cdomain eurodir.eu --cdnsips 81.93.162.172,81.93.166.172 --cdnssuffix eurodir.eu --chostname testbox01 --datacenter EDSA --cvlan ED-ORTUS-STAGE --cgw 10.29.34.1/24 --cips 10.29.34.9/24 --fqdn testbox01.eurodir.eu --dest-folder 'BAT/New VMs' --start STARTVM --bootstrap TRUE --distro centos6-clean --run-list 'role[VMware-BAT_base]' --ssh-user root --ssh-password xxxxxxxxx
DEBUG: Using configuration from /root/.chef/knife.rb
/usr/lib64/ruby/gems/1.8/gems/knife-vsphere-0.1.8/lib/chef/knife/vsphere_vm_clone.rb:248:in `generate_clone_spec': undefined method `config' for #<RbVmomi::VIM::Network:0x7f802a874798> (NoMethodError)
	from /usr/lib64/ruby/gems/1.8/gems/knife-vsphere-0.1.8/lib/chef/knife/vsphere_vm_clone.rb:187:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/chef-0.10.8/lib/chef/knife.rb:391:in `run_with_pretty_exceptions'
	from /usr/lib64/ruby/gems/1.8/gems/chef-0.10.8/lib/chef/knife.rb:166:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/chef-0.10.8/lib/chef/application/knife.rb:128:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/chef-0.10.8/bin/knife:25
	from /usr/bin/knife:19:in `load'
	from /usr/bin/knife:19
```

I believe the issue lies in "vsphere_vm_clone.rb" around line 248 where it tries to determine the switch port.

```
switch_port = RbVmomi::VIM.DistributedVirtualSwitchPortConnection(:switchUuid => network.config.distributedVirtualSwitch.uuid ,:portgroupKey => network.key)
```

We don't utilise a distributed virtual switch.  Is there a way around this?

**Comment by DennisBP** [comment]
Could we close this bug report?

**Comment by swalberg** [comment]
Yea this should have been fixed a while ago. Closing, thanks for checking in.
