### ISSUE TITLE
error during clone vm in latest release

### ISSUE THREAD

**Issue by dzabel** [ezrapagel/knife-vsphere#167]
If i try to clone a vm with 1.2.0 gem installed i get this error:

```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-vsphere-1.2.0/lib/chef/knife/vsphere_vm_clone.rb:25:in `<class:VsphereVmClone>': uninitialized constant Chef::Knife::VsphereVmClone::CustomizationHelper (NameError)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-vsphere-1.2.0/lib/chef/knife/vsphere_vm_clone.rb:21:in `<top (required)>'
	from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
	from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
	from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
	from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:128:in `load_commands'
	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:209:in `run'
	from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:53:in `load'
	from /usr/bin/knife:53:in `<main>'
```

**Comment by swalberg** [comment]
Thanks for the fix. `gem install knife-vsphere` to get 1.2.1 please.
