### ISSUE TITLE
wait sysprep throwing errors

### ISSUE THREAD

**Issue by gwagner** [ezrapagel/knife-vsphere#170]
When running this command `knife vsphere vm wait sysprep "valid-machine-name" --config "/tmp/knife594717f65fc16aac06499b215504ba62cca07c30.rb" --folder "/Util" -VV` i am getting the following error:

```
/usr/local/rvm/gems/ruby-2.1.3/gems/knife-vsphere-1.2.1/lib/chef/knife/vsphere_vm_wait_sysprep.rb:47:in `run': undefined local variable or method `get_vim_connection' for #<Chef::Knife::VsphereVmWaitSysprep:0x000000057af3a0> (NameError)
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/lib/chef/knife.rb:215:in `run'
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/lib/chef/application/knife.rb:142:in `run'
	from /usr/local/rvm/gems/ruby-2.1.3/gems/chef-12.4.0/bin/knife:25:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.3/bin/knife:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.3/bin/knife:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by gwagner** [comment]
Looks like this commit fixes it: https://github.com/ezrapagel/knife-vsphere/commit/5bfbaebb1b3ebc652ba985da29cf34395e388a3d

I modified my file locally and it seems to work.

Sorry for the noise!

**Comment by swalberg** [comment]
Sorry Geoffrey. I'll be pushing a release soon. Just about to put up a PR that was sent to me over email.
